// sem_5/ueLibre/vueJS/vuejs-app/src/Pages/Livres/Update.vue
<script>
export default {
    data() {
        return {
            id: null, // Stocke l'ID du livre à modifier
            titre: '',
            auteur: '',
            disponible: 'oui'
        };
    },
    methods: {
        async loadLivre(id) {
            try {
                const response = await fetch(`http://localhost:3000/livres/${id}`);
                if (!response.ok) {
                    throw new Error('Erreur HTTP ! statut : ' + response.status);
                }
                const livre = await response.json();
                this.id = livre.id;
                this.titre = livre.titre;
                this.auteur = livre.auteur;
                this.disponible = livre.disponible ? "oui" : "non";
            } catch (e) {
                console.error("Erreur lors du chargement :", e);
            }
        },
        async updateLivre() {
            try {
                const response = await fetch(`http://localhost:3000/livres/${this.id}`, {
                    method: 'PUT', // Utilisation de la méthode PUT
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        titre: this.titre,
                        auteur: this.auteur,
                        disponible: this.disponible === "oui" // Conversion en Boolean
                    })
                });
                if (!response.ok) {
                    throw new Error('Erreur HTTP ! statut : ' + response.status);
                }
                this.$router.push('/'); // Redirection après la mise à jour
            } catch (e) {
                console.error("Erreur lors de la mise à jour :", e);
            }
        }
    },
    created() {
        const id = this.$route.params.id; // Récupérer l'ID depuis l'URL
        if (id) {
            this.loadLivre(id);
        }
    }
};
</script>

<template>
    <div>
        <h1>Modifier un livre</h1>
        <form @submit.prevent="updateLivre">
            <label for="titre">Titre</label>
            <input type="text" id="titre" v-model="titre">
            <label for="auteur">Auteur</label>
            <input type="text" id="auteur" v-model="auteur">
            <label for="disponible">Disponibilité</label>
            <select id="disponible" v-model="disponible">
                <option value="oui">Oui</option>
                <option value="non">Non</option>
            </select>
            <button type="submit">Modifier</button>
        </form>
    </div>
</template>

// sem_5/ueLibre/AngularJS/my-app/src/app/components/livre/update/update.component.ts
import { NgIf } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Livre } from '../../../models/livre';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { LivreService } from '../../../service/livre.service';

@Component({
  selector: 'app-update',
  standalone: true,
  imports: [FormsModule, NgIf, RouterLink],
  templateUrl: './update.component.html',
  styleUrl: './update.component.css'
})
export class UpdateComponent implements OnInit {
  livre: Livre = {
    id: 0,
    titre: '',
    auteur: '',
    disponible: true
  };

  constructor(
    private route: ActivatedRoute,
    private livreService: LivreService,
    private router: Router
  ) {}

  ngOnInit(): void {
    const id = Number(this.route.snapshot.params['id']); // Conversion en number
    this.livreService.getLivreById(id).subscribe({
      next: (data) => {
        this.livre = data;
      },
      error: (err) => {
        console.error('Erreur lors du chargement du livre', err);
      }
    });
  }

  updateLivre(): void {
    if (this.livre.id !== undefined) { // Vérification que l'ID est défini
      this.livreService.updateLivre(this.livre.id, this.livre).subscribe({
        next: () => {
          this.router.navigate(['/livres']);
        },
        error: (err) => {
          console.error('Erreur lors de la mise à jour du livre', err);
        }
      });
    } else {
      console.error("Erreur : l'ID du livre est indéfini !");
    }
  }  
}

<div class="container mt-4">
    <h2>Modifier un Livre</h2>
    <form (ngSubmit)="updateLivre()" #livreForm="ngForm">
      <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" id="titre" [(ngModel)]="livre.titre" name="titre" required #titre="ngModel">
        <div *ngIf="titre.invalid && (titre.touched || titre.dirty)" class="text-danger">
          Le titre est requis.
        </div>
      </div>
      <div class="mb-3">
        <label for="auteur" class="form-label">Auteur</label>
        <input type="text" class="form-control" id="auteur" [(ngModel)]="livre.auteur" name="auteur" required #auteur="ngModel">
        <div *ngIf="auteur.invalid && (auteur.touched || auteur.dirty)" class="text-danger">
          L'auteur est requis.
        </div>
      </div>
      <div class="mb-3">
        <label for="disponible" class="form-label">Disponible</label>
        <select class="form-select" id="disponible" [(ngModel)]="livre.disponible" name="disponible" required #disponible="ngModel">
          <option value="true">Oui</option>
          <option value="false">Non</option>
        </select>
        <div *ngIf="disponible.invalid && (disponible.touched || disponible.dirty)" class="text-danger">
          La disponibilité est requise.
        </div>
      </div>
      <button type="submit" class="btn btn-warning" [disabled]="livreForm.invalid">Mettre à jour</button>
      <a routerLink="/livres" class="btn btn-secondary">Retour à la liste</a>
    </form>
  </div>
